[build]
builder = "NIXPACKS"
buildCommand = "npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend"

[deploy]
startCommand = "node backend/src/db/migrate.js && node backend/src/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
